### ISSUE TITLE
White screen on all examples.

### ISSUE THREAD

**Issue by Gustan13** [devkitPro/nds-examples#18]
Hi there, I've been trying to compile the nds examples that come with devkitPro using msys2 but to no avail. When I use Make to
compile, everything works, but when I try to test any of the examples on an emulator, the emulator only shows a white screen.

I have made no changes to the devkitPro tooling, I am using Windows 10 and I tried melonDs and DeSmuME.

I have no idea on how to recreate this problem because the only thing I did was install the devkitPro and run make on msys2.

**Comment by WinterMute** [comment]
All of the examples work fine on hardware, preferably when launched via [hbmenu](https://github.com/devkitPro/nds-hb-menu). DeSmuME and melonDS have both recently received updates for libnds v2/calico so you may need to go find a recent build of those emulators. It sounds like @Arisotura is planning a melonDS release candidate really soon though. https://melonds.kuribo64.net/comments.php?id=215

Generally speaking if binaries don't work in emulators but do work on hardware it should be considered an emulator bug & reported to the relevant emulator team. We upstreamed some fixes for melonDS a few days ago.

**Comment by DaMatrix** [comment]
I was getting a white screen on all the examples on my console. Updating my TWiLightMenu installation fixed booting examples from the SD card, but I still get a white screen when booting examples over dsilink+Unlaunch's builtin wifiboot.

Is there any way I can get wifiboot working with the new libnds v2 environment? I assume the root problem is wifiboot not setting up all the console state correctly before jumping into the ROM code, but since there don't appear to be any updates available for Unlaunch, I'm not really sure what my next steps should be. Is it known which changes in libnds v2 specifically resulted in emulators/older ROM bootstraps failing to launch?
